In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('BankChurners.csv')

#### Mean of column names
CLIENTNUM : Client number. Unique identifier for the customer holding the account\
Attrition_Flag : Internal event (customer activity) variable\
Customer_Age : Customer's Age in Years\
Gender : M=Male, F=Female\
Dependent_count : Number of dependents\
Education_Level : Educational Qualification of the account holder\
Marital_Status : Married, Single, Divorced, Unknown\
Income_Category : Annual Income Category of the account holder\
Card_Category : Type of Card (Blue, Silver, Gold, Platinum)\
Months_on_book : Period of relationship with bank\
Total_Relationship_Count : Total no. of products held by the customer\
Months_Inactive_12_mon : No. of months inactive in the last 12 months\
Contacts_Count_12_mon : No. of Contacts in the last 12 months\
Credit_Limit : Credit Limit on the Credit Card\
Total_Revolving_Bal : Total Revolving Balance on the Credit Card\
Avg_Open_To_Buy : Open to Buy Credit Line (Average of last 12 months)\
Total_Amt_Chng_Q4_Q1 : Change in Transaction Amount (Q4 over Q1)\
Total_Trans_Amt : Total Transaction Amount (Last 12 months)\
Total_Trans_Ct : Total Transaction Count (Last 12 months)\
Total_Ct_Chng_Q4_Q1 : Change in Transaction Count (Q4 over Q1)\
Avg_Utilization_Ratio : Average Card Utilization Ratio

In [2]:
# 最後兩欄無意義，先刪除
df = df.iloc[:,0:21]
df

CLIENTNUM     Attrition_Flag  Customer_Age Gender  Dependent_count  \
0      768805383  Existing Customer            45      M                3   
1      818770008  Existing Customer            49      F                5   
2      713982108  Existing Customer            51      M                3   
3      769911858  Existing Customer            40      F                4   
4      709106358  Existing Customer            40      M                3   
...          ...                ...           ...    ...              ...   
10122  772366833  Existing Customer            50      M                2   
10123  710638233  Attrited Customer            41      M                2   
10124  716506083  Attrited Customer            44      F                1   
10125  717406983  Attrited Customer            30      M                2   
10126  714337233  Attrited Customer            43      F                2   

      Education_Level Marital_Status Income_Category Card_Category  \
0         High School        Married     $60K - $80K          Blue   
1            Graduate         Single  Less than $40K          Blue   
2            Graduate        Married    $80K - $120K          Blue   
3         High School        Unknown  Less than $40K          Blue   
4          Uneducated        Married     $60K - $80K          Blue   
...               ...            ...             ...           ...   
10122        Graduate         Single     $40K - $60K          Blue   
10123         Unknown       Divorced     $40K - $60K          Blue   
10124     High School        Married  Less than $40K          Blue   
10125        Graduate        Unknown     $40K - $60K          Blue   
10126        Graduate        Married  Less than $40K        Silver   

       Months_on_book  ...  Months_Inactive_12_mon  Contacts_Count_12_mon  \
0                  39  ...                       1                      3   
1                  44  ...                       1                      2   
2                  36  ...                       1                      0   
3                  34  ...                       4                      1   
4                  21  ...                       1                      0   
...               ...  ...                     ...                    ...   
10122              40  ...                       2                      3   
10123              25  ...                       2                      3   
10124              36  ...                       3                      4   
10125              36  ...                       3                      3   
10126              25  ...                       2                      4   

       Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
0           12691.0                  777          11914.0   
1            8256.0                  864           7392.0   
2            3418.0                    0           3418.0   
3            3313.0                 2517            796.0   
4            4716.0                    0           4716.0   
...             ...                  ...              ...   
10122        4003.0                 1851           2152.0   
10123        4277.0                 2186           2091.0   
10124        5409.0                    0           5409.0   
10125        5281.0                    0           5281.0   
10126       10388.0                 1961           8427.0   

       Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0                     1.335             1144              42   
1                     1.541             1291              33   
2                     2.594             1887              20   
3                     1.405             1171              20   
4                     2.175              816              28   
...                     ...              ...             ...   
10122                 0.703            15476             117   
10123                 0.804             8764              69   
10124  

檢查是否有缺失值

In [7]:
# True: 有空值  False: 無空值
df.isnull().any()

CLIENTNUM                   False
Attrition_Flag              False
Customer_Age                False
Gender                      False
Dependent_count             False
Education_Level             False
Marital_Status              False
Income_Category             False
Card_Category               False
Months_on_book              False
Total_Relationship_Count    False
Months_Inactive_12_mon      False
Contacts_Count_12_mon       False
Credit_Limit                False
Total_Revolving_Bal         False
Avg_Open_To_Buy             False
Total_Amt_Chng_Q4_Q1        False
Total_Trans_Amt             False
Total_Trans_Ct              False
Total_Ct_Chng_Q4_Q1         False
Avg_Utilization_Ratio       False
dtype: bool

檢查是否有重複的編號

In [19]:
# false代表無重複
df['CLIENTNUM'].duplicated().any()

False

In [3]:
df.drop(columns=['CLIENTNUM'],inplace=True)

In [4]:
df

Attrition_Flag  Customer_Age Gender  Dependent_count  \
0      Existing Customer            45      M                3   
1      Existing Customer            49      F                5   
2      Existing Customer            51      M                3   
3      Existing Customer            40      F                4   
4      Existing Customer            40      M                3   
...                  ...           ...    ...              ...   
10122  Existing Customer            50      M                2   
10123  Attrited Customer            41      M                2   
10124  Attrited Customer            44      F                1   
10125  Attrited Customer            30      M                2   
10126  Attrited Customer            43      F                2   

      Education_Level Marital_Status Income_Category Card_Category  \
0         High School        Married     $60K - $80K          Blue   
1            Graduate         Single  Less than $40K          Blue   
2            Graduate        Married    $80K - $120K          Blue   
3         High School        Unknown  Less than $40K          Blue   
4          Uneducated        Married     $60K - $80K          Blue   
...               ...            ...             ...           ...   
10122        Graduate         Single     $40K - $60K          Blue   
10123         Unknown       Divorced     $40K - $60K          Blue   
10124     High School        Married  Less than $40K          Blue   
10125        Graduate        Unknown     $40K - $60K          Blue   
10126        Graduate        Married  Less than $40K        Silver   

       Months_on_book  Total_Relationship_Count  Months_Inactive_12_mon  \
0                  39                         5                       1   
1                  44                         6                       1   
2                  36                         4                       1   
3                  34                         3                       4   
4                  21                         5                       1   
...               ...                       ...                     ...   
10122              40                         3                       2   
10123              25                         4                       2   
10124              36                         5                       3   
10125              36                         4                       3   
10126              25                         6                       2   

       Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  \
0                          3       12691.0                  777   
1                          2        8256.0                  864   
2                          0        3418.0                    0   
3                          1        3313.0                 2517   
4                          0        4716.0                    0   
...                      ...           ...                  ...   
10122                      3        4003.0                 1851   
10123                      3        4277.0                 2186   
10124                      4        5409.0                    0   
10125                      3        5281.0                    0   
10126                      4       10388.0                 1961   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0              11914.0                 1.335             1144              42   
1               7392.0                 1.541             1291              33   
2               3418.0                 2.594             1887              20   
3                796.0                 1.405             1171              20   
4               4716.0                 2.175              816              28   
...                ...                   ...              ...             ...   
10122           2152.0                 0.703            15476             117   
10123           2091.0

將Attrition_Flag中的Existing Customer改成1，Attrited Customer改成0

In [11]:
df['Attrition_Flag'].unique()

array(['Existing Customer', 'Attrited Customer'], dtype=object)

In [5]:
df['Attrition_Flag'] = df['Attrition_Flag'].map({'Existing Customer':1, 'Attrited Customer':0})

In [14]:
df['Attrition_Flag'].unique()

array([1, 0], dtype=int64)

In [17]:
# 計算繼續留存客戶的比例
df['Attrition_Flag'].sum()/df.shape[0]

0.8393403772094401

兩個類別的人數差異大，需要特別注意

In [20]:
df.dtypes

CLIENTNUM                     int64
Attrition_Flag                int64
Customer_Age                  int64
Gender                       object
Dependent_count               int64
Education_Level              object
Marital_Status               object
Income_Category              object
Card_Category                object
Months_on_book                int64
Total_Relationship_Count      int64
Months_Inactive_12_mon        int64
Contacts_Count_12_mon         int64
Credit_Limit                float64
Total_Revolving_Bal           int64
Avg_Open_To_Buy             float64
Total_Amt_Chng_Q4_Q1        float64
Total_Trans_Amt               int64
Total_Trans_Ct                int64
Total_Ct_Chng_Q4_Q1         float64
Avg_Utilization_Ratio       float64
dtype: object

Gender, Education_Level, Marital_Status, Income_Category, Income_Category為類別型態

In [6]:
# 將gender改成 M => 1  F => 0
df['Gender'] = df['Gender'].map({'M':1, 'F':0})

In [31]:
df.columns

Index(['Attrition_Flag', 'Customer_Age', 'Gender', 'Dependent_count',
       'Education_Level', 'Marital_Status', 'Income_Category', 'Card_Category',
       'Months_on_book', 'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio'],
      dtype='object')

In [7]:
# 將類別資料(字串)轉換成one hot encoder
df_dum = pd.get_dummies(df)

In [26]:
df_dum.columns

Index(['Attrition_Flag', 'Customer_Age', 'Gender', 'Dependent_count',
       'Months_on_book', 'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio',
       'Education_Level_College', 'Education_Level_Doctorate',
       'Education_Level_Graduate', 'Education_Level_High School',
       'Education_Level_Post-Graduate', 'Education_Level_Uneducated',
       'Education_Level_Unknown', 'Marital_Status_Divorced',
       'Marital_Status_Married', 'Marital_Status_Single',
       'Marital_Status_Unknown', 'Income_Category_$120K +',
       'Income_Category_$40K - $60K', 'Income_Category_$60K - $80K',
       'Income_Category_$80K - $120K', 'Income_Category_Less than $40K',
       'Income_Category_Unknown', 'Card_Category_Blue', 'Card_Category_Gold',
       'Card_Category_Platinum', 'Card_C

#### K-Nearest Neighbours

In [27]:
from sklearn import neighbors
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix


# 建立X, y
X = df_dum.drop(columns=['CLIENTNUM','Attrition_Flag'])
y = df_dum['Attrition_Flag']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)

model = neighbors.KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)


X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
num_correct_samples = accuracy_score(y_test, y_pred, normalize=False)
con_matrix = confusion_matrix(y_test, y_pred)

print('number of correct sample: {}'.format(num_correct_samples))
print('accuracy: {}'.format(accuracy))
print('confusion matrix: \n{}'.format(con_matrix))

number of correct sample: 1736
accuracy: 0.8568608094768015
confusion matrix: 
[[ 124  230]
 [  60 1612]]


#### Random Forest

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.datasets import load_iris
from sklearn import tree

# 建立X, y
X = df_dum.drop(columns=['Attrition_Flag'])
y = df_dum['Attrition_Flag']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)

model = RandomForestClassifier(max_depth=5, n_estimators=1000,n_jobs=-1)
#model = RandomForestClassifier(max_depth=6, n_estimators=1000)
model.fit(X_train, y_train)

X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
num_correct_samples = accuracy_score(y_test, y_pred, normalize=False)
con_matrix = confusion_matrix(y_test, y_pred)

print('number of correct sample: {}'.format(num_correct_samples))
print('accuracy: {}'.format(accuracy))
print('con_matrix: \n{}'.format(con_matrix))

number of correct sample: 1848
accuracy: 0.912142152023692
con_matrix: 
[[ 154  145]
 [  33 1694]]


In [10]:
# 將模型存成pickle檔
import pickle
pickle.dump(model, open('RF_credit.pkl','wb'))

In [13]:
# demo
# input data use get_dummies()
import pandas as pd
df = pd.DataFrame({'cat':['a','b','c','d'],'val':[1,2,5,10]})
df1 = pd.get_dummies(pd.DataFrame({'cat':['a'],'val':[1]}))
dummies_frame = pd.get_dummies(df)
df1.reindex(columns = dummies_frame.columns, fill_value=0)

val  cat_a  cat_b  cat_c  cat_d
0    1      1      0      0      0

In [17]:
col = ['Customer_Age', 'Gender', 'Dependent_count',
       'Months_on_book', 'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio',
       'Education_Level_College', 'Education_Level_Doctorate',
       'Education_Level_Graduate', 'Education_Level_High School',
       'Education_Level_Post-Graduate', 'Education_Level_Uneducated',
       'Education_Level_Unknown', 'Marital_Status_Divorced',
       'Marital_Status_Married', 'Marital_Status_Single',
       'Marital_Status_Unknown', 'Income_Category_$120K +',
       'Income_Category_$40K - $60K', 'Income_Category_$60K - $80K',
       'Income_Category_$80K - $120K', 'Income_Category_Less than $40K',
       'Income_Category_Unknown', 'Card_Category_Blue', 'Card_Category_Gold',
       'Card_Category_Platinum', 'Card_Category_Silver']

In [18]:
d = {
 "Customer_Age": 30,
 "Gender": 1,
 "Dependent_count": 3,
 "Education_Level": "Graduate",
 "Marital_Status": "Married",
 "Income_Category": "Less than $40K",
 "Card_Category": "Blue",
 "Months_on_book": 35,
 "Total_Relationship_Count": 3,
 "Months_Inactive_12_mon": 2,
 "Contacts_Count_12_mon": 2,
 "Credit_Limit": 4700,
 "Total_Revolving_Bal": 1200,
 "Avg_Open_To_Buy": 3400,
 "Total_Amt_Chng_Q4_Q1": 1.5,
 "Total_Trans_Amt": 1800,
 "Total_Trans_Ct": 42,
 "Total_Ct_Chng_Q4_Q1": 0.85,
 "Avg_Utilization_Ratio": 0.145}

In [19]:
# 建立新的資料
input_df = pd.DataFrame(d,index=['input'])
input_df

Customer_Age  Gender  Dependent_count Education_Level Marital_Status  \
input            30       1                3        Graduate        Married   

      Income_Category Card_Category  Months_on_book  Total_Relationship_Count  \
input  Less than $40K          Blue              35                         3   

       Months_Inactive_12_mon  Contacts_Count_12_mon  Credit_Limit  \
input                       2                      2          4700   

       Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
input                 1200             3400                   1.5   

       Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  \
input             1800              42                 0.85   

       Avg_Utilization_Ratio  
input                  0.145

In [22]:
input_dum = pd.get_dummies(input_df)
input_dum = input_dum.reindex(columns = col, fill_value=0)

In [23]:
model.predict(input_dum)

array([1], dtype=int64)

In [ ]:
# 測試模型的pickle
with open('GBRmodel.pkl', 'rb') as f:
    model_load = pickle.load(f)

y_pred = model_load.predict(X_test)
r2_score(y_test, y_pred)