![alt text](./images/ML_01.jpg)

![alt text](./images/ML_02.jpg)

![alt text](./images/ML_03.jpg)

![alt text](./images/ML_04.jpg)

In [50]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from os import listdir

# read image data 
s='./data/'
file_list = []
for i in range(10):
    file_list += [('./data/{}/'.format(i) + n) for n in listdir('./data/{}'.format(i))]
file_list

['./data/0/0-1.bmp',
 './data/0/0-10.bmp',
 './data/0/0-2.bmp',
 './data/0/0-3.bmp',
 './data/0/0-4.bmp',
 './data/0/0-5.bmp',
 './data/0/0-6.bmp',
 './data/0/0-7.bmp',
 './data/0/0-8.bmp',
 './data/0/0-9.bmp',
 './data/1/1-1.bmp',
 './data/1/1-10.bmp',
 './data/1/1-2.bmp',
 './data/1/1-3.bmp',
 './data/1/1-4.bmp',
 './data/1/1-5.bmp',
 './data/1/1-6.bmp',
 './data/1/1-7.bmp',
 './data/1/1-8.bmp',
 './data/1/1-9.bmp',
 './data/2/2--2.bmp',
 './data/2/2-1.bmp',
 './data/2/2-10.bmp',
 './data/2/2-3.bmp',
 './data/2/2-4.bmp',
 './data/2/2-5.bmp',
 './data/2/2-6.bmp',
 './data/2/2-7.bmp',
 './data/2/2-8.bmp',
 './data/2/2-9.bmp',
 './data/3/3-1.bmp',
 './data/3/3-10.bmp',
 './data/3/3-2.bmp',
 './data/3/3-3.bmp',
 './data/3/3-4.bmp',
 './data/3/3-5.bmp',
 './data/3/3-6.bmp',
 './data/3/3-7.bmp',
 './data/3/3-8.bmp',
 './data/3/3-9.bmp',
 './data/4/4-1.bmp',
 './data/4/4-10.bmp',
 './data/4/4-2.bmp',
 './data/4/4-3.bmp',
 './data/4/4-4.bmp',
 './data/4/4-5.bmp',
 './data/4/4-6.bmp',
 './dat

In [32]:
# read first file
image=cv2.imread(file_list[0],cv2.IMREAD_GRAYSCALE)

cv2.imshow('image',image) 
# waiting time(ms), 0 mean any stop key
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [18]:
# write your code here

print(image.shape) 

# 
np.unique(image)

(240, 240)


array([  0, 255], dtype=uint8)

In [33]:
sum(image==0).sum()

2692

In [40]:
# extract each image as feature vector
# use 6*6 grid to represent each origin image
b_list=[]
for file in file_list:
    image=cv2.imread(file,cv2.IMREAD_GRAYSCALE)
    b = []
    for i in range(6):
        for j in range(6):
            area=image[i*40:(i+1)*40,j*40:(j+1)*40]
            b.append(sum(area==0).sum())
    b_list.append(b)

In [42]:
dataset = np.array(b_list)
dataset[0:5,]

array([[  0,   0, 178, 286,   6,   0,   0,   0, 333,  22, 320,   0,   0,
          0, 291,   0, 285,   0,   0,   0, 361, 151, 284,   0,   0,   0,
          4, 171,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 265, 313,  28,   0,   0,   0, 324,   3, 326,   0,   0,
         20, 272,   0, 286,   0,   0,   0, 319,   0, 308,   0,   0,   0,
        207, 306, 111,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,  24,  19,   0,   0,   0,   0, 426, 311, 181,   0,   0,
          0, 295,   0, 293,   0,   0,   0, 371, 168, 198,   0,   0,   0,
         28, 200,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  10, 357,  10,   0,   0,   0, 304,  35, 323,   0,   0,   0,
        280,   0, 292,   0,   0,   0, 262, 138, 335,   0,   0,   0,   0,
        178,  13,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 248, 202,   0,   0,   0, 141, 207, 185, 167,   0,   0,
        292,   0,   0, 294,   0,   0, 232,  86, 182, 166,   0,   0,   0,
        317, 230,   0,   0,   0,  

In [51]:
# write your code here
labels = np.array([[i]*10 for i in range(10)])
labels = labels.flatten()
#print(dataset.shape)
#print(labels.shape)

In [52]:
from sklearn import neighbors
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix

# split data into training data and testing data
X_train, X_test, y_train, y_test = train_test_split(dataset, labels, test_size=0.2)


# write your code here


print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(80, 36)
(80,)
(20, 36)
(20,)


In [53]:
# build model and evaluate your result
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)

model = neighbors.KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

# write your code here
X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
num_correct_samples = accuracy_score(y_test, y_pred, normalize=False)
con_matrix = confusion_matrix(y_test, y_pred)

print('number of correct sample: {}'.format(num_correct_samples))
print('accuracy: {}'.format(accuracy))
print('confusion matrix: \n{}'.format(con_matrix))

number of correct sample: 17
accuracy: 0.85
confusion matrix: 
[[1 0 0 0 1 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0]
 [0 1 0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 2]]
